inherit_from: .rubocop_todo.yml

Styles/LeadingCommentSpace:
  Exclude:
    - 'spec/teaspoon_env.rb'

Style/FileName:
  Exclude:
    - 'Gemfile'

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Style/SpaceInsideBrackets:
  Enabled: False
