inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Styles/LeadingCommentSpace:
  Exclude:
    - 'spec/teaspoon_env.rb'

Style/FileName:
  Exclude:
    - 'Gemfile'

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
