inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '|'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - 'config/application.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'

Style/AlignParameters:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
