inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'

Style/AlignParameters:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
