inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
