inherit_from: .rubocop_todo.yml

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/teaspoon_env.rb'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/SpaceInsideBrackets:
  Enabled: False

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/ExtraSpacing:
  Exclude:
    - 'db/tenant_schema.rb'
