default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + 1 %>
  timeout: 5000
  host: <%= ENV.fetch('DB_HOST', nil) %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: ledger_development

test:
  <<: *default
  database: ledger_test

production:
  <<: *default
  database: ledger_production
