default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ledger_development

test:
  <<: *default
  database: ledger_test

production:
  <<: *default
  database: ledger_production
